"""
Shared build configuration for SessionPrep.
Used by both Nuitka and PyInstaller build scripts to ensure consistency.
"""
import os
import sys
import platform
import importlib.util

# Core application metadata
APP_NAME = "sessionprep"

# Paths
BASE_DIR = os.path.dirname(os.path.abspath(__file__))
ICON_DIR = os.path.join(BASE_DIR, "sessionprepgui", "res")
VERSION_FILE = os.path.join(BASE_DIR, "sessionpreplib", "_version.py")
BUILD_VERSION_FILE = os.path.join(BASE_DIR, "sessionpreplib", "_build_version.py")
_BUILD_VERSION_MARKER = "# Generated by SessionPrep build scripts."
BUILD_VERSION_MODULE = "sessionpreplib._build_version"

# Output directory names
DIST_PYINSTALLER = "dist_pyinstaller"
DIST_NUITKA = "dist_nuitka"

# macOS app bundle display name (CFBundleName / .app directory name)
MACOS_APP_NAME = "SessionPrep"

# Platform Logic
_PLATFORM_SUFFIXES = {
    "Windows": "win",
    "Darwin": "macos",
    "Linux": "linux",
}

def get_platform_suffix() -> str:
    """Return platform-arch suffix, e.g. 'win-x64' or 'macos-arm64'."""
    plat = _PLATFORM_SUFFIXES.get(platform.system(), platform.system().lower())
    arch = platform.machine().lower()
    # Normalize arch names
    arch = {"x86_64": "x64", "amd64": "x64", "aarch64": "arm64"}.get(arch, arch)
    return f"{plat}-{arch}"

def get_executable_name(base_name):
    """Returns the full executable name with platform suffix and extension."""
    suffix = get_platform_suffix()
    full_name = f"{base_name}-{suffix}"
    if sys.platform == "win32":
        return f"{full_name}.exe"
    return full_name


def _load_version_module():
    spec = importlib.util.spec_from_file_location(
        "sessionprep_build_version", VERSION_FILE
    )
    if spec is None or spec.loader is None:
        raise RuntimeError(f"Could not load version module: {VERSION_FILE}")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def get_version(*, strict: bool = True) -> str:
    """Return the Git-derived application version for build tooling."""
    return _load_version_module().get_version(strict=strict)


def write_build_version_file(version: str | None = None) -> str:
    """Write the frozen-build version module and return the version."""
    resolved = version or get_version(strict=True)
    with open(BUILD_VERSION_FILE, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(f"{_BUILD_VERSION_MARKER}\n")
        fh.write(f'BUILD_VERSION = "{resolved}"\n')
    return resolved


def remove_build_version_file() -> None:
    """Remove the generated frozen-build version module if we created it."""
    if not os.path.exists(BUILD_VERSION_FILE):
        return
    with open(BUILD_VERSION_FILE, encoding="utf-8") as fh:
        first_line = fh.readline().strip()
    if first_line == _BUILD_VERSION_MARKER:
        os.remove(BUILD_VERSION_FILE)


def _resolve_icon() -> str | None:
    """Return the best icon path for the current platform."""
    res_dir = os.path.join(BASE_DIR, "sessionprepgui", "res")
    system = platform.system()
    if system == "Windows":
        candidates = ["sessionprep.ico", "sessionprep.png"]
    elif system == "Darwin":
        candidates = ["sessionprep.icns", "sessionprep.png"]
    else:
        candidates = ["sessionprep.png"]
    for name in candidates:
        path = os.path.join(res_dir, name)
        if os.path.isfile(path):
            return path
    return None

# Target Definitions
TARGETS = {
    "cli": {
        "script": "sessionprep.py",
        "name": get_executable_name("sessionprep"),
        "console": True,
        # Nuitka specific
        "nuitka_exclude": [
            "PySide6", "shiboken6", "sessionprepgui", "tkinter", "unittest"
        ],
        "nuitka_plugins": [],
        "nuitka_include_modules": [BUILD_VERSION_MODULE],
        "include_data": [],
        
        # PyInstaller specific
        "pyinstaller_hidden_imports": [
            "rich", "rich.console", "rich.table", "rich.panel", "rich.progress",
            BUILD_VERSION_MODULE,
        ],
        "pyinstaller_windowed": False,
    },
    "gui": {
        "script": "sessionprep-gui.py",
        "name": get_executable_name("sessionprep-gui"),
        "console": False, 
        "icon": _resolve_icon(),
        
        # Nuitka specific
        "nuitka_exclude": [
            "rich", "curses", "tkinter", "unittest", "pdb"
        ],
        "nuitka_plugins": ["pyside6"],
        "nuitka_include_modules": [BUILD_VERSION_MODULE],
        "include_data": [
            (ICON_DIR, os.path.join("sessionprepgui", "res"))
        ],
        
        # PyInstaller specific
        "pyinstaller_hidden_imports": [
            "PySide6", "PySide6.QtCore", "PySide6.QtGui", "PySide6.QtWidgets",
            "sounddevice",
            BUILD_VERSION_MODULE,
        ],
        "pyinstaller_windowed": True,
    }
}
