"""Build metadata bridge for Git-derived SessionPrep versions."""

from __future__ import annotations

import importlib.util
from pathlib import Path

from setuptools import setup


_BUILD_VERSION_MARKER = "# Generated by SessionPrep build scripts."


def _version() -> str:
    path = Path(__file__).parent / "sessionpreplib" / "_version.py"
    spec = importlib.util.spec_from_file_location("sessionprep_setup_version", path)
    if spec is None or spec.loader is None:
        raise RuntimeError(f"Could not load version module: {path}")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    version = module.get_version(strict=True)
    build_version_path = path.parent / "_build_version.py"
    build_version_path.write_text(
        f'{_BUILD_VERSION_MARKER}\nBUILD_VERSION = "{version}"\n',
        encoding="utf-8",
        newline="\n",
    )
    return version


setup(version=_version())
